apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.23"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::514684045883:role/LabRole
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t2.medium
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::514684045883:role/LabRole
