apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: final
type: Opaque
data:
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: final
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ASIAXPVMPJI52DVFPFPI
  AWS_SECRET_ACCESS_KEY: 1yfyGUIP0XguLPu14r/tKDhOplp+RVM06PJpmS+/

---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-image-pull-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJZT1VSX1VTRVJOQU1FIiwKICAgICAgInBhc3N3b3JkIjogIllPVVJfUEFTU1dPUkQiLAogICAgICAiZW1haWwiOiAiWU9VUl9FTUFJTCIKICAgIH0KICB9Cn0KCg==
